@startuml
|Kunde|
start
    :vælg vare;
    :læg i kurv;
    :indtast postnummer (levering);
    :beregner fragtpris|
    :får fragtpris;
    :tilføj til kurv;
    :popup|
fork
if(shop videre) then
end if
    :vælg vare;

fork again
    :gå til kurv;
endfork
    :gå til kassen;
    :udfyld oplysninger;
    if(sender mail)
    :betal;
    :modtager styklist;
    endif

|Sælger|
    :modtager forspørgsel|
    :opretter styklist;
    :Sender ordre;
stop
@enduml
