@startuml
|Kunde|
start
    :forside;
    :vælg
    byg selv
    carport;
    :udfyld specifikation
    om ønskede carport;
    :udfyld kontakt oplysninger;
    :modtag
    ordre bekræftelse
    stykliste og tegning|
stop

@enduml
