@startuml
|Kunde|
start
label sp_lab1
    :forside;
    :vælg
    byg selv
    carport;
    :udfyld specifikation
    om ønskede carport;
    :udfyld kontakt oplysninger;
    label sp_lab2
    :modtag
    ordre bekræftelse
    stykliste og tegning|

    label sp_lab1
    goto sp_lab2
stop

@enduml
