@startuml
'https://plantuml.com/class-diagram


object Kunde
object Carport
object Tilbud
object Hjemmeside
object Ordrer
object Stykliste
object Samlevejledning

Kunde --* "1-1" Hjemmeside
Carport "1-M"--* Hjemmeside
Tilbud "1-1"--* Ordrer
Ordrer "1-1" --|> Stykliste
Ordrer "1-1" --|> Samlevejledning
Carport "1-1" --* Tilbud
Kunde "1-M"--* Tilbud





@enduml