@startuml
'https://plantuml.com/class-diagram

object Kunde
object Carport
object Sælger
object Tilbud
object Beregninssystem
object Butik

Sælger  --* Butik : has-a
Kunde --* Sælger
Beregninssystem --* Sælger
Tilbud --* Beregninssystem
Kunde --* Tilbud
Carport --* Butik




@enduml